# Generated by Django 4.1.7 on 2023-04-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('password_repeat', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
